apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-demo-microservice-01
  labels:
    app: basic-demo-microservice-01
spec:
  replicas: 3
  selector:
    matchLabels:
      app: basic-demo-microservice-01
  template:
    metadata:
      labels:
        app: basic-demo-microservice-01
    spec:
      serviceAccountName: node-reader-sa
      containers:
        - name: basic-demo-microservice-01
          image: 933673765333.dkr.ecr.us-east-1.amazonaws.com/basic-demo-microservice-01:latest
          ports:
            - containerPort: 80
          env:
            - name: APP_VERSION
              value: "1.0.0"
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
---
apiVersion: v1
kind: Service
metadata:
  name: basic-demo-microservice-01-service
spec:
  selector:
    app: basic-demo-microservice-01
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
